name: publish

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  publish:

    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Publish packages
        uses: gradle/gradle-build-action@v2.9.0
        with:
          arguments: publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          H4KT_REPO_USERNAME: ${{ secrets.H4KT_REPO_USERNAME }}
          H4KT_REPO_PASSWORD: ${{ secrets.H4KT_REPO_PASSWORD }}
